from typing import Dict, TypedDict

class _Status(TypedDict):
    data: int

class _RTC(TypedDict):
    data: Dict[str, int]

class PiJuice:
    def __init__(self, bus: int, address: int) -> None: ...
    def GetChargeLevel(self) -> _Status: ...
    def GetTime(self) -> _RTC: ...
    def SetTime(self, time_dict: Dict[str, int]) -> _Status: ...
    def pijuice(self) -> None: ...
