# config-sample.yaml
# Weather Display - Example Configuration
# --------------------------------------
# Copy this file to config.yaml and customize for your setup

# Location & API credentials
lat: 33.8852         # Your latitude
lon: -84.5144        # Your longitude
city: "Smyrna, GA"  # Display name for your location
api_key: "your-openweather-api-key"  # Get from openweathermap.org

# Display preferences
units: imperial      # 'imperial' for °F/mph or 'metric' for °C/m/s
timezone: "America/New_York"  # Your local timezone

# Time formats (strftime format strings)
time_format_general: "%-I:%M %p"    # Example: 3:45 PM
time_format_hourly: "%-I %p"        # Example: 3 PM
time_format_daily: "%a"             # Example: Mon
time_format_full_date: "%A, %B %-d" # Example: Monday, January 3

# How much forecast data to show
hourly_count: 8        # number of hourly entries in the strip (1–48)
daily_count: 5         # number of daily entries (1–7)

# Base refresh cadence (minutes)
# The program adjusts this value based on multiple battery SoC thresholds
# and other system conditions to optimize power consumption.
refresh_minutes: 120

# Display settings (pixels)
# The display width and height should match the actual resolution of your display.
display_width: 1872
display_height: 1404