# config-sample.yaml
# Weather Display - Example Configuration
# --------------------------------------
# Copy this file to config.yaml and customize for your setup

# Location & API credentials
lat: 42.774         # Your latitude
lon: -78.787        # Your longitude
city: "Orchard Park, NY"  # Display name for your location - GO BILLS!
api_key: "${OWM_API_KEY}"  # Get from openweathermap.org and load to your environment

# Display preferences
units: imperial      # 'imperial' for °F/mph or 'metric' for °C/m/s
timezone: "America/New_York"  # Your local timezone

# Time formats (strftime format strings)
time_format_general: "%-I:%M %p"    # Example: 3:45 PM
time_format_hourly: "%-I %p"        # Example: 3 PM
time_format_daily: "%a"             # Example: Mon
time_format_full_date: "%A, %B %-d" # Example: Monday, January 3

# How much forecast data to show
hourly_count: 8        # number of hourly entries in the strip (1–48)
daily_count: 5         # number of daily entries (1–7)

# Base refresh cadence (minutes)
# The program adjusts this value based on multiple battery SoC thresholds
# and other system conditions to optimize power consumption.
refresh_minutes: 120

# Display settings (pixels)
# The display width and height should match the actual resolution of your display.
display_width: 1872
display_height: 1404
vcom_volts: -1.45 # VCOM voltage for the display, printed on the display ribbon