[tool.mypy]
python_version = "3.9"
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
strict_optional = true

[[tool.mypy.overrides]]
module = [
  "waveshare_epaper_it8951.*",
  "IT8951.*",
  "pijuice.*"
]
ignore_missing_imports = true
follow_imports = "skip"