name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ─────────────────────────────────────────────
      # SVG build toolchain (Inkscape + xmlstarlet + Node)
      # ─────────────────────────────────────────────
      - name: Install Inkscape & xmlstarlet
        run: |
          sudo apt-get update
          sudo apt-get install -y inkscape xmlstarlet

      - name: Set up Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Node dev-dependencies
        run: npm ci

      - name: Build icons (trim → color-fix → sprite)
        run: npm run icons:build

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pip install poetry==1.8.2

      - name: Install deps (prod + dev)
        run: |
          poetry install --with dev

      - name: Ruff lint
        run: poetry run ruff check .

      - name: Pyright type-check
        run: poetry run pyright

      - name: Run tests
        run: poetry run pytest -q
      - name: CLI smoke test
        run: poetry run weather --help